// Generated by CoffeeScript 1.10.0
(function() {
  var count, counter, customLoggerD, custom_message_handler, draggable_keylistener_handler, draggable_orientationsensor_handler, draggable_touchpad_handler, register, registerPlayer, registeredIDs, unregisteredPlayer;

  customLoggerD = function() {

    /*customLogger "Delay" */
    return stk.framework.timer(1000, counter);
  };

  stk.framework.delay(500, customLoggerD);

  custom_message_handler = function(msg) {
    return register(msg);
  };

  draggable_orientationsensor_handler = function(msg) {
    return register(msg);
  };

  draggable_touchpad_handler = function(msg) {
    return register(msg);
  };

  draggable_keylistener_handler = function(msg) {
    console.log(msg);
    return register(msg);
  };


  /* Register your handler */

  stk.framework.register_handler('custommessage', custom_message_handler);

  stk.framework.register_handler('draggable_touchpad', draggable_touchpad_handler);

  stk.framework.register_handler('draggable_keylistener', draggable_keylistener_handler);

  unregisteredPlayer = 6;

  count = 30;

  registeredIDs = [];

  register = function(msg) {
    if (unregisteredPlayer >= 1 && msg !== void 0) {
      return registerPlayer(msg.envelop.clientid);
    }
  };

  registerPlayer = function(clientid) {
    var id;
    console.log("try to register", clientid);
    if (registeredIDs.indexOf(clientid) <= -1) {
      registeredIDs.push(clientid);
      id = "player" + (7 - unregisteredPlayer);
      stk.framework.storeData({
        id: clientid
      }, true);
      $('#' + id).css('opacity', 1);
      unregisteredPlayer -= 1;
      console.log("registerPlayer", clientid);
      return console.log(stk.framework.getData(true));
    }
  };

  counter = function() {
    if (unregisteredPlayer < 6) {
      if (count > 0) {
        count -= 1;
        $('#countdown').html(count);
      } else {
        console.log("start!");
        location.href = "index.html";
      }
    }
    return true;
  };

}).call(this);
