// Generated by CoffeeScript 1.10.0
(function() {
  var count, counter, register, registerPlayer, registeredIDs, restart, unregisteredPlayer;

  restart = function() {
    console.log("Restart");
    return location.href = "start.html";
  };

  stk.framework.delay(6000, restart);

  unregisteredPlayer = 6;

  count = 30;

  registeredIDs = [];

  register = function(msg) {
    if (unregisteredPlayer >= 1 && msg !== void 0) {
      return registerPlayer(msg.envelop.clientid);
    }
  };

  registerPlayer = function(clientid) {
    var id;
    console.log("try to register", clientid);
    if (registeredIDs.indexOf(clientid) <= -1) {
      registeredIDs.push(clientid);
      id = "player" + (7 - unregisteredPlayer);
      stk.framework.storeData({
        id: clientid
      }, true);
      $('#' + id).css('opacity', 1);
      unregisteredPlayer -= 1;
      console.log("registerPlayer", clientid);
      return console.log(stk.framework.getData(true));
    }
  };

  counter = function() {
    if (unregisteredPlayer < 6) {
      if (count > 0) {
        count -= 1;
        $('#countdown').html(count);
      } else {
        console.log("start!");
        location.href = "index.html";
      }
    }
    return true;
  };

}).call(this);
