// Generated by CoffeeScript 1.10.0

/*

The compiled custom_head.js will be included in the html head section after
global css definitions and jquery

Define your functions that do not use socket.io and stk-framework objects here if you want them to be loaded before the body. Otherwise define your stuff in custom_end.coffee/custom_end.js
 */

(function() {


}).call(this);
